/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtorJogador.java
 *
 * Created on Jul 8, 2011, 12:21:20 PM
 */
package gui;

import javax.swing.*;
import java.util.*;
import paciencia.*;


/**
 *
 * @author Matheus
 */
public class AtorJogador extends JFrame implements Observer {

    /** Creates new form AtorJogador */
    public AtorJogador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPMesa = new javax.swing.JPanel();
        guiBaralhoOponente = new gui.GUIBaralho();
        guiBagacoOponente = new gui.GUIBagaco();
        guiRestritoOponente = new gui.GUIRestrito();
        guiSequencia1 = new gui.GUISequencia();
        guiSequencia3 = new gui.GUISequencia();
        guiSequencia2 = new gui.GUISequencia();
        guiSequencia4 = new gui.GUISequencia();
        guiPilha1 = new gui.GUIPilha();
        guiPilha2 = new gui.GUIPilha();
        guiPilha3 = new gui.GUIPilha();
        guiPilha4 = new gui.GUIPilha();
        guiPilha5 = new gui.GUIPilha();
        guiPilha6 = new gui.GUIPilha();
        guiPilha7 = new gui.GUIPilha();
        guiPilha8 = new gui.GUIPilha();
        guiSequencia5 = new gui.GUISequencia();
        guiSequencia8 = new gui.GUISequencia();
        guiSequencia7 = new gui.GUISequencia();
        guiSequencia6 = new gui.GUISequencia();
        guiBaralho = new gui.GUIBaralho();
        guiBagaco = new gui.GUIBagaco();
        guiRestrito = new gui.GUIRestrito();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPChat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTAEnviarMensagem = new javax.swing.JTextArea();
        jBEnviar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPMesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout guiBaralhoOponenteLayout = new javax.swing.GroupLayout(guiBaralhoOponente);
        guiBaralhoOponente.setLayout(guiBaralhoOponenteLayout);
        guiBaralhoOponenteLayout.setHorizontalGroup(
            guiBaralhoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiBaralhoOponenteLayout.setVerticalGroup(
            guiBaralhoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiBagacoOponenteLayout = new javax.swing.GroupLayout(guiBagacoOponente);
        guiBagacoOponente.setLayout(guiBagacoOponenteLayout);
        guiBagacoOponenteLayout.setHorizontalGroup(
            guiBagacoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiBagacoOponenteLayout.setVerticalGroup(
            guiBagacoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiRestritoOponenteLayout = new javax.swing.GroupLayout(guiRestritoOponente);
        guiRestritoOponente.setLayout(guiRestritoOponenteLayout);
        guiRestritoOponenteLayout.setHorizontalGroup(
            guiRestritoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiRestritoOponenteLayout.setVerticalGroup(
            guiRestritoOponenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia1Layout = new javax.swing.GroupLayout(guiSequencia1);
        guiSequencia1.setLayout(guiSequencia1Layout);
        guiSequencia1Layout.setHorizontalGroup(
            guiSequencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia1Layout.setVerticalGroup(
            guiSequencia1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia3Layout = new javax.swing.GroupLayout(guiSequencia3);
        guiSequencia3.setLayout(guiSequencia3Layout);
        guiSequencia3Layout.setHorizontalGroup(
            guiSequencia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia3Layout.setVerticalGroup(
            guiSequencia3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia2Layout = new javax.swing.GroupLayout(guiSequencia2);
        guiSequencia2.setLayout(guiSequencia2Layout);
        guiSequencia2Layout.setHorizontalGroup(
            guiSequencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia2Layout.setVerticalGroup(
            guiSequencia2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia4Layout = new javax.swing.GroupLayout(guiSequencia4);
        guiSequencia4.setLayout(guiSequencia4Layout);
        guiSequencia4Layout.setHorizontalGroup(
            guiSequencia4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia4Layout.setVerticalGroup(
            guiSequencia4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha1Layout = new javax.swing.GroupLayout(guiPilha1);
        guiPilha1.setLayout(guiPilha1Layout);
        guiPilha1Layout.setHorizontalGroup(
            guiPilha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha1Layout.setVerticalGroup(
            guiPilha1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha2Layout = new javax.swing.GroupLayout(guiPilha2);
        guiPilha2.setLayout(guiPilha2Layout);
        guiPilha2Layout.setHorizontalGroup(
            guiPilha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha2Layout.setVerticalGroup(
            guiPilha2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha3Layout = new javax.swing.GroupLayout(guiPilha3);
        guiPilha3.setLayout(guiPilha3Layout);
        guiPilha3Layout.setHorizontalGroup(
            guiPilha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha3Layout.setVerticalGroup(
            guiPilha3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha4Layout = new javax.swing.GroupLayout(guiPilha4);
        guiPilha4.setLayout(guiPilha4Layout);
        guiPilha4Layout.setHorizontalGroup(
            guiPilha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha4Layout.setVerticalGroup(
            guiPilha4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha5Layout = new javax.swing.GroupLayout(guiPilha5);
        guiPilha5.setLayout(guiPilha5Layout);
        guiPilha5Layout.setHorizontalGroup(
            guiPilha5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha5Layout.setVerticalGroup(
            guiPilha5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha6Layout = new javax.swing.GroupLayout(guiPilha6);
        guiPilha6.setLayout(guiPilha6Layout);
        guiPilha6Layout.setHorizontalGroup(
            guiPilha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha6Layout.setVerticalGroup(
            guiPilha6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha7Layout = new javax.swing.GroupLayout(guiPilha7);
        guiPilha7.setLayout(guiPilha7Layout);
        guiPilha7Layout.setHorizontalGroup(
            guiPilha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha7Layout.setVerticalGroup(
            guiPilha7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiPilha8Layout = new javax.swing.GroupLayout(guiPilha8);
        guiPilha8.setLayout(guiPilha8Layout);
        guiPilha8Layout.setHorizontalGroup(
            guiPilha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiPilha8Layout.setVerticalGroup(
            guiPilha8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia5Layout = new javax.swing.GroupLayout(guiSequencia5);
        guiSequencia5.setLayout(guiSequencia5Layout);
        guiSequencia5Layout.setHorizontalGroup(
            guiSequencia5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia5Layout.setVerticalGroup(
            guiSequencia5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia8Layout = new javax.swing.GroupLayout(guiSequencia8);
        guiSequencia8.setLayout(guiSequencia8Layout);
        guiSequencia8Layout.setHorizontalGroup(
            guiSequencia8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia8Layout.setVerticalGroup(
            guiSequencia8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia7Layout = new javax.swing.GroupLayout(guiSequencia7);
        guiSequencia7.setLayout(guiSequencia7Layout);
        guiSequencia7Layout.setHorizontalGroup(
            guiSequencia7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia7Layout.setVerticalGroup(
            guiSequencia7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiSequencia6Layout = new javax.swing.GroupLayout(guiSequencia6);
        guiSequencia6.setLayout(guiSequencia6Layout);
        guiSequencia6Layout.setHorizontalGroup(
            guiSequencia6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        guiSequencia6Layout.setVerticalGroup(
            guiSequencia6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiBaralhoLayout = new javax.swing.GroupLayout(guiBaralho);
        guiBaralho.setLayout(guiBaralhoLayout);
        guiBaralhoLayout.setHorizontalGroup(
            guiBaralhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiBaralhoLayout.setVerticalGroup(
            guiBaralhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiBagacoLayout = new javax.swing.GroupLayout(guiBagaco);
        guiBagaco.setLayout(guiBagacoLayout);
        guiBagacoLayout.setHorizontalGroup(
            guiBagacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiBagacoLayout.setVerticalGroup(
            guiBagacoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guiRestritoLayout = new javax.swing.GroupLayout(guiRestrito);
        guiRestrito.setLayout(guiRestritoLayout);
        guiRestritoLayout.setHorizontalGroup(
            guiRestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        guiRestritoLayout.setVerticalGroup(
            guiRestritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jLabel1.setText("Baralho");

        jLabel2.setText("Bagaço");

        jLabel3.setText("Restrito");

        jLabel4.setText("Sequências");

        jLabel5.setText("Sequências");

        jLabel6.setText("Pilhas");

        jLabel7.setText("Pilhas");

        jLabel8.setText("Baralho");

        jLabel9.setText("Bagaço");

        jLabel10.setText("Restrito");

        javax.swing.GroupLayout jPMesaLayout = new javax.swing.GroupLayout(jPMesa);
        jPMesa.setLayout(jPMesaLayout);
        jPMesaLayout.setHorizontalGroup(
            jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMesaLayout.createSequentialGroup()
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(guiRestritoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(guiRestrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(guiBaralho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(guiBagaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPMesaLayout.createSequentialGroup()
                                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guiSequencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiSequencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiSequencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiSequencia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(guiPilha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiPilha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiPilha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guiPilha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(guiPilha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guiPilha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(guiPilha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(guiPilha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPMesaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guiSequencia5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiSequencia6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiSequencia7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiSequencia8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPMesaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))))
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3))
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPMesaLayout.createSequentialGroup()
                                .addComponent(guiBaralhoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guiBagacoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPMesaLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(83, 83, 83))
        );
        jPMesaLayout.setVerticalGroup(
            jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guiBagacoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiBaralhoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guiRestritoOponente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPMesaLayout.createSequentialGroup()
                            .addComponent(guiPilha5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPMesaLayout.createSequentialGroup()
                            .addComponent(guiSequencia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiSequencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiSequencia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiSequencia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPMesaLayout.createSequentialGroup()
                            .addComponent(guiPilha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(guiPilha4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPMesaLayout.createSequentialGroup()
                        .addComponent(guiSequencia5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiSequencia6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiSequencia7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guiSequencia8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guiRestrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiBagaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guiBaralho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPChat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTAChat.setColumns(20);
        jTAChat.setEditable(false);
        jTAChat.setRows(5);
        jScrollPane1.setViewportView(jTAChat);

        JTAEnviarMensagem.setColumns(20);
        JTAEnviarMensagem.setRows(3);
        jScrollPane2.setViewportView(JTAEnviarMensagem);

        jBEnviar.setText("Enviar");
        jBEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarActionPerformed(evt);
            }
        });

        jLabel11.setText("Chat");

        javax.swing.GroupLayout jPChatLayout = new javax.swing.GroupLayout(jPChat);
        jPChat.setLayout(jPChatLayout);
        jPChatLayout.setHorizontalGroup(
            jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPChatLayout.createSequentialGroup()
                .addGroup(jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPChatLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPChatLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(jBEnviar))))
                    .addGroup(jPChatLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );
        jPChatLayout.setVerticalGroup(
            jPChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPChatLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEnviar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPChat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPMesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtorJogador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JTAEnviarMensagem;
    private gui.GUIBagaco guiBagaco;
    private gui.GUIBagaco guiBagacoOponente;
    private gui.GUIBaralho guiBaralho;
    private gui.GUIBaralho guiBaralhoOponente;
    private gui.GUIPilha guiPilha1;
    private gui.GUIPilha guiPilha2;
    private gui.GUIPilha guiPilha3;
    private gui.GUIPilha guiPilha4;
    private gui.GUIPilha guiPilha5;
    private gui.GUIPilha guiPilha6;
    private gui.GUIPilha guiPilha7;
    private gui.GUIPilha guiPilha8;
    private gui.GUIRestrito guiRestrito;
    private gui.GUIRestrito guiRestritoOponente;
    private gui.GUISequencia guiSequencia1;
    private gui.GUISequencia guiSequencia2;
    private gui.GUISequencia guiSequencia3;
    private gui.GUISequencia guiSequencia4;
    private gui.GUISequencia guiSequencia5;
    private gui.GUISequencia guiSequencia6;
    private gui.GUISequencia guiSequencia7;
    private gui.GUISequencia guiSequencia8;
    private javax.swing.JButton jBEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPChat;
    private javax.swing.JPanel jPMesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAChat;
    // End of variables declaration//GEN-END:variables


    protected Paciencia mesa;
    protected String nomeJogador;
    protected String nomeOponente;

    /**
     * 
     * @return 
     */
    public void habilitarInterface() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void desabilitarInterface() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param mensagem
     * @return 
     */
    public void popupMensagem(String mensagem) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param estadoInicial
     * @return 
     */
    public void criarMesa(EstadoInicial estadoInicial) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void consultarRegras() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param ipServidor
     * @param nome
     * @return 
     */
    public void conectar(String ipServidor, String nome) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void desconectar() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getNome() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getIpServidor() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getTextoMensagem() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param o
     * @param arg
     * @return 
     */
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param mensagem
     * @return 
     */
    public void chatMensagem(String mensagem) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param o
     * @param arg
     * @return 
     */
    

}
