/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AtorJogador.java
 *
 * Created on Jul 8, 2011, 12:21:20 PM
 */
package gui;

import javax.swing.*;
import java.util.*;
import paciencia.*;


/**
 *
 * @author Matheus
 */
public class AtorJogador extends JFrame implements Observer {

    /** Creates new form AtorJogador */
    public AtorJogador() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AtorJogador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


    protected Paciencia mesa;
    protected String nomeJogador;
    protected String nomeOponente;

    /**
     * 
     * @return 
     */
    public void habilitarInterface() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void desabilitarInterface() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param mensagem
     * @return 
     */
    public void popupMensagem(String mensagem) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param estadoInicial
     * @return 
     */
    public void criarMesa(EstadoInicial estadoInicial) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void consultarRegras() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param ipServidor
     * @param nome
     * @return 
     */
    public void conectar(String ipServidor, String nome) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public void desconectar() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getNome() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getIpServidor() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @return 
     */
    public String getTextoMensagem() {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param o
     * @param arg
     * @return 
     */
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param mensagem
     * @return 
     */
    public void chatMensagem(String mensagem) {
        throw new UnsupportedOperationException();
    }

    /**
     * 
     * @param o
     * @param arg
     * @return 
     */
    

}
