/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIRestrito.java
 *
 * Created on Jul 8, 2011, 5:01:35 PM
 */
package gui;

import java.io.Serializable;
import javax.swing.JPanel;

/**
 *
 * @author Matheus
 */
public class GUIRestrito extends JPanel implements Serializable{

    /** Creates new form GUIRestrito */
    public GUIRestrito() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(57, 81));
        setMinimumSize(new java.awt.Dimension(57, 81));
        setPreferredSize(new java.awt.Dimension(57, 81));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
